name: Deploy Chipnik Monitor API (Self-Hosted)

on:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - "chipnik_monitor/**"
  workflow_dispatch:
  workflow_call:

env:
  APP_DIR: chipnik_monitor
  SERVICE_PORT: "8080"

jobs:
  deploy:
    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image
        working-directory: ${{ env.APP_DIR }}
        run: |
          docker build -t chipnik-monitor:latest .

      - name: Stop previous container (if any)
        run: |
          docker rm -f chipnik-monitor || true

      - name: Run container
        env:
          EARTHDATA_BEARER_TOKEN: ${{ secrets.EARTHDATA_BEARER_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          DAYS_BACK_LIMIT: ${{ vars.DAYS_BACK_LIMIT || 2000 }}
          SERVICE_PORT: ${{ env.SERVICE_PORT }}
        run: |
          docker run -d --name chipnik-monitor \
            --restart=always \
            -p ${SERVICE_PORT}:${SERVICE_PORT} \
            -e EARTHDATA_BEARER_TOKEN \
            -e MONGO_URI \
            -e MONGO_DB \
            -e DAYS_BACK_LIMIT \
            chipnik-monitor:latest \
            uvicorn api:app --host 0.0.0.0 --port ${SERVICE_PORT}

      - name: Health check
        run: |
          sleep 3
          docker ps --format '{{.Names}}' | grep -q '^chipnik-monitor$'
          curl -fsS http://127.0.0.1:${{ env.SERVICE_PORT }}/docs >/dev/null
          echo "Chipnik Monitor container is up"